// Per-locale URL slugs for each tool/landing page.
//
// The key of each record is a stable English page ID — never renamed, used for
// imports and internal refs. The value maps each Locale to the slug used in
// that locale's URL. English slugs equal the page ID (keeps existing URLs
// stable). Other locales are translated for SEO (French users search for
// "gif en url" not "gif-to-url").
//
// This file is partially auto-maintained: English entries are authored here;
// non-English entries are filled by scripts/translate-landing.mjs using
// OpenRouter (google/gemini-3.1-flash-lite-preview). Re-running the script is
// idempotent — existing non-English entries are preserved.

import type { Locale } from '../config';

export type PageKey =
  | 'gif-to-url'
  | 'heic-to-jpg'
  | 'png-to-url'
  | 'jpg-to-url'
  | 'webp-to-url'
  | 'photo-to-url'
  | 'screenshot-to-url'
  | 'image-url-generator'
  | 'image-embed-code-generator'
  | 'image-url-for-chatgpt'
  | 'image-to-url-for-whatsapp'
  | 'image-to-url-for-html'
  | 'image-to-url-vercel'
  | 'image-hosting-for-wordpress'
  | 'image-hosting-for-discord'
  | 'image-hosting-for-ebay'
  | 'image-hosting-for-email-signatures'
  | 'image-hosting-for-forums'
  | 'image-hosting-for-github-readme'
  | 'image-hosting-for-google-forms'
  | 'image-hosting-for-google-sheets'
  | 'image-hosting-for-newsletters'
  | 'image-hosting-for-notion'
  | 'image-hosting-for-shopify'
  | 'free-image-hosting'
  | 'free-image-cdn'
  | 'ai-image-hosting'
  | 'anonymous-image-upload'
  | 'bulk-image-upload'
  | 'direct-image-link'
  | 'permanent-image-hosting'
  | 'imgbb-alternative'
  | 'imgur-alternative'
  | 'cloudinary-alternative'
  // Cluster A — format-pair converters (browser-side)
  | 'png-to-jpg'
  | 'jpg-to-png'
  | 'webp-to-jpg'
  | 'webp-to-png'
  | 'png-to-webp'
  | 'jpg-to-webp'
  | 'png-to-pdf'
  | 'jpg-to-pdf'
  | 'heic-to-png'
  | 'heic-to-pdf'
  // Cluster B — utilities
  | 'image-compressor'
  | 'image-resizer'
  | 'image-to-base64'
  | 'base64-to-image'
  | 'favicon-generator'
  | 'about'
  | 'contact'
  | 'content-guidelines';

export type LocaleSlugMap = Partial<Record<Locale, string>>;

// Only English slugs authored here. Non-English slugs are added by
// scripts/translate-landing.mjs (it edits this file in place, filling entries).
export const SLUGS: Record<PageKey, LocaleSlugMap> = {
  'gif-to-url': { en: 'gif-to-url', fr: 'gif-vers-url', de: 'gif-zu-url-konvertieren', ar: 'تحويل-gif-إلى-url', hi: 'gif-को-url-में-बदलें', es: 'convertir-gif-a-url', ja: 'gif-を-url-に変換', 'zh-Hans': 'gif-转-url', id: 'ubah-gif-ke-url', vi: 'chuyen-doi-gif-sang-url', 'pt-BR': 'gif-para-url', tr: 'gif-url-donusturucu', tl: 'gif-to-url-tagalog', pl: 'gif-na-url', nl: 'gif-naar-url-omzetten', it: 'gif-a-url', bn: 'gif-কে-url-এ-রূপান্তর', fa: 'تبدیل-gif-به-url', ur: 'gif-کو-url-میں-تبدیل', ru: 'gif-v-url', th: 'แปลง-gif-เป็น-url', ko: 'gif를-url로-변환', sw: 'geuza-gif-kuwa-url', ms: 'tukar-gif-ke-url', ta: 'gif-ஐ-url-ஆக-மாற்று', mr: 'gif-ला-url-मध्ये-बदला', te: 'gif-ని-url-గా-మార్చు', 'zh-Hant': '將-gif-轉換為-url' },
  'heic-to-jpg': { en: 'heic-to-jpg', hi: 'heic-क-jpg-म-बदल', fr: 'convertir-heic-en-jpg', de: 'heic-zu-jpg-konverter', es: 'convertir-heic-a-jpg', ja: 'heic-を-jpg-に変換', 'zh-Hans': 'heic-转-jpg-转换器', id: 'konversi-heic-ke-jpg', vi: 'chuyen-doi-heic-sang-jpg', 'pt-BR': 'converter-heic-para-jpg', tr: 'heic-jpg-donusturucu', tl: 'convert-heic-sa-jpg', pl: 'konwerter-heic-na-jpg', nl: 'heic-naar-jpg-converteren-converteren', it: 'convertire-heic-in-jpg', ar: 'تحويل-heic-إلى-jpg', bn: 'heic-থেকে-jpg-কনভার্টার', fa: 'تبدیل-heic-به-jpg', ur: 'heic-کو-jpg-میں-تبدیل', ru: 'konverter-heic-v-jpg', th: 'แปลง-heic-เป็น-jpg', ko: 'heic-jpg-변환기', sw: 'badilisha-heic-kwenda-jpg', ms: 'tukar-heic-ke-jpg', ta: 'heic-to-jpg-கன்வெர்ட்டர்', mr: 'heic-to-jpg-कन्व्हर्टर', te: 'heic-to-jpg-కన్వర్టర్', 'zh-Hant': 'heic-轉-jpg-轉換器' },
  'png-to-url': { en: 'png-to-url', hi: 'png-को-url-में-बदलें', fr: 'convertir-png-en-url', de: 'png-in-url-umwandeln', es: 'convertir-png-a-url', ja: 'png-画像-url-変換', 'zh-Hans': 'png-zhuan-url-lian-jie', id: 'ubah-png-ke-url', vi: 'chuyen-doi-png-thanh-url', 'pt-BR': 'converter-png-para-url', tr: 'png-resmini-url-linke-cevir', tl: 'i-convert-ang-png-sa-url', pl: 'konwersja-png-na-url', nl: 'png-naar-url-converteren', it: 'converti-png-in-url', ar: 'تحويل-صورة-png-إلى-رابط', bn: 'png-কে-url-লিংকে-রূপান্তর', fa: 'تبدیل-عکس-png-به-لینک', ur: 'png-کو-url-میں-بدلیں', ru: 'konvertirovat-png-v-ssylku', th: 'แปลง-png-เป็น-url', ko: 'png-이미지를-url로-변환', sw: 'badilisha-png-kuwa-url', ms: 'tukar-png-kepada-url', ta: 'png-படத்தை-url-ஆக-மாற்றவும்', mr: 'png-ला-url-मध्ये-रूपांतरित-करा', te: 'png-చిత్రాన్ని-url-గా-మార్చండి', 'zh-Hant': 'png-轉-url-連結' },
  'jpg-to-url': { en: 'jpg-to-url', hi: 'jpg-को-url-में-बदलें', es: 'convertir-jpg-a-url', fr: 'convertir-jpg-en-url', de: 'jpg-in-url-umwandeln', ja: 'jpg-画像-url-変換', 'zh-Hans': 'jpg-zhuan-url-lianjie', id: 'ubah-gambar-jpg-ke-url', vi: 'chuyen-doi-jpg-thanh-url', 'pt-BR': 'converter-jpg-para-url', tr: 'jpg-resmini-url-linke-cevir', tl: 'i-convert-ang-jpg-sa-url', pl: 'konwersja-jpg-na-url', nl: 'jpg-naar-url-converteren', it: 'converti-jpg-in-url', ar: 'تحويل-صورة-jpg-إلى-رابط', bn: 'jpg-ছবি-url-লিঙ্কে-রূপান্তর', fa: 'تبدیل-عکس-jpg-به-لینک', ur: 'jpg-تصویر-کو-url-میں-بدلیں', ru: 'konvertirovat-jpg-v-ssylku', th: 'แปลง-jpg-เป็น-url', ko: 'jpg-이미지를-url로-변환', sw: 'badilisha-jpg-kuwa-url', ms: 'tukar-gambar-jpg-kepada-url', ta: 'jpg-படத்தை-url-ஆக-மாற்றவும்', mr: 'jpg-इमेज-url-लिंक-मध्ये-रूपांतरित-करा', te: 'jpg-చిత్రాన్ని-url-గా-మార్చండి', 'zh-Hant': 'jpg-轉-url-連結' },
  'webp-to-url': { en: 'webp-to-url', hi: 'webp-को-url-में-बदलें', es: 'convertir-webp-a-url', fr: 'convertir-webp-en-url', de: 'webp-in-url-umwandeln', ja: 'webp-url-henkan', 'zh-Hans': 'webp-zhuan-url', id: 'ubah-webp-ke-url', vi: 'chuyen-doi-webp-sang-url', 'pt-BR': 'converter-webp-para-url', tr: 'webp-dosyasini-url-yap', tl: 'webp-sa-url-converter', nl: 'webp-naar-url-converter', it: 'converti-webp-in-url', ar: 'تحويل-webp-إلى-رابط', bn: 'webp-থেকে-url-কনভার্টার', fa: 'تبدیل-webp-به-لینک', ur: 'webp-کو-url-میں-بدلیں', ru: 'webp-v-ssylku', th: 'แปลง-webp-เป็น-url', ko: 'webp-이미지-url-변환', sw: 'geuza-webp-kuwa-url', ms: 'tukar-webp-ke-url', ta: 'webp-ஐ-url-ஆக-மாற்றுங்கள்', mr: 'webp-चे-url-मध्ये-रूपांतरण', te: 'webp-ను-url-గా-మార్చండి', 'zh-Hant': 'webp-轉-url', pl: 'webp-na-url-konwerter' },
  'photo-to-url': { en: 'photo-to-url', hi: 'फोटो-को-url-में-बदलें', es: 'convertir-foto-a-url', fr: 'convertir-photo-en-url', de: 'foto-in-url-umwandeln', ja: '写真-url-変換', 'zh-Hans': '照片转链接', id: 'ubah-foto-ke-url', vi: 'chuyen-anh-thanh-url', 'pt-BR': 'foto-para-link', tr: 'fotografi-url-ye-donustur', tl: 'larawan-sa-url', pl: 'zdjecie-na-link', nl: 'foto-naar-url-omzetten', it: 'converti-foto-in-url', ar: 'تحويل-الصورة-إلى-رابط', bn: 'ছবি-থেকে-ইউআরএল', fa: 'تبدیل-عکس-به-لینک', ur: 'تصویر-کو-یو-آر-ایل-میں-بدلیں', ru: 'foto-v-ssylku', th: 'แปลง-รูปภาพ-เป็น-ลิงก์', ko: '사진-url-변환', sw: 'badilisha-picha-kuwa-url', ms: 'tukar-gambar-kepada-url', ta: 'புகைப்படத்தை-url-ஆக-மாற்று', mr: 'फोटो-चे-url-मध्ये-रूपांतर', te: 'ఫోటోను-url-గా-మార్చండి', 'zh-Hant': '照片轉網址' },
  'screenshot-to-url': { en: 'screenshot-to-url', hi: 'स्क्रीनशॉट-को-url-में-बदलें', es: 'convertir-captura-a-url', fr: 'convertir-capture-ecran-en-url', de: 'screenshot-in-url-umwandeln', ja: 'スクリーンショット-url-変換', 'zh-Hans': '截图转链接', id: 'ubah-screenshot-jadi-url', vi: 'chuyen-anh-chup-man-hinh-thanh-url', 'pt-BR': 'converter-screenshot-para-url', tr: 'ekran-goruntusunu-url-yap', tl: 'screenshot-sa-url', pl: 'zrzut-ekranu-na-url', nl: 'screenshot-naar-url-omzetten', it: 'screenshot-in-url-convertire', ar: 'تحويل-لقطة-الشاشة-إلى-رابط', fa: 'تبدیل-اسکرین-شات-به-لینک', ur: 'اسکرین-شاٹ-کو-یو-آر-ایل-میں-بدلیں', ru: 'skrinshot-v-ssylku', th: 'แปลง-ภาพหน้าจอ-เป็น-ลิงก์', ko: '스크린샷-url-변환', sw: 'badilisha-picha-kuwa-url', ms: 'tukar-screenshot-kepada-url', ta: 'திரைப்படத்தை-url-ஆக-மாற்று', mr: 'स्क्रीनशॉट-चे-url-मध्ये-रूपांतर', te: 'స్క్రీన్షాట్-ను-url-గా-మార్చండి', 'zh-Hant': '螢幕截圖-轉-連結', bn: 'স্ক্রিনশট-থেকে-ইউআরএল' },
  'image-url-generator': { en: 'image-url-generator', hi: 'इमेज-को-url-में-बदलें', es: 'generador-de-url-de-imagen', fr: 'generateur-url-image-gratuit', de: 'bild-zu-url-konverter', ja: '画像-url-生成', 'zh-Hans': '图片转链接生成器', id: 'generator-url-gambar-gratis', vi: 'trinh-tao-url-anh', tr: 'resim-url-olusturucu', tl: 'libreng-image-url-generator', pl: 'darmowy-generator-url-obrazow', nl: 'gratis-afbeelding-url-generator', bn: 'ছবি-থেকে-ইউআরএল-জেনারেটর', fa: 'تبدیل-تصویر-به-لینک', ur: 'تصویر-کو-url-میں-بدلیں', th: 'สร้าง-url-รูปภาพ-ฟรี', ko: '이미지-url-생성기', sw: 'jenereta-ya-url-ya-picha', ms: 'penjana-url-imej-percuma', mr: 'इमेज-url-जनरेटर', te: 'చిత్రం-నుండి-url-జనరేటర్', 'zh-Hant': '圖片轉網址產生器', 'pt-BR': 'gerador-de-url-de-imagem', it: 'generatore-url-immagini-gratuito', ar: 'مولد-رابط-الصورة-مجانا', ru: 'besplatnyy-generator-ssylok-na-izobrazheniya', ta: 'படத்தை-url-ஆக-மாற்றுங்கள்' },
  'image-embed-code-generator': { en: 'image-embed-code-generator', hi: 'इमेज-एम्बेड-कोड-जनरेटर', es: 'generador-codigo-incrustar-imagenes', fr: 'generateur-code-embed-image', de: 'bild-embed-code-generator', ja: '画像-埋め込み-コード-生成', 'zh-Hans': '图片-嵌入-代码-生成器', id: 'generator-kode-embed-gambar', vi: 'tao-ma-nhung-anh', 'pt-BR': 'gerador-codigo-incorporacao-imagem', tr: 'gorsel-gomme-kodu-olusturucu', tl: 'generator-ng-embed-code', pl: 'generator-kodu-embed-obrazow', nl: 'generator-voor-afbeeldingscodes', it: 'generatore-codice-embed-immagini', ar: 'مولد-كود-تضمين-الصور', bn: 'ইমেজ-এমবেড-কোড-জেনারেটর', fa: 'تولیدکننده-کد-جایگذاری-تصویر', ur: 'image-embed-code-جنریٹر', ru: 'generator-koda-izobrazheniy', th: 'เครื่องมือ-สร้าง-โค้ด-ฝังรูปภาพ', ko: '이미지-임베드-코드-생성기', sw: 'jenereta-ya-embed-code-picha', ms: 'penjana-kod-benam-imej', ta: 'image-embed-code-generator', mr: 'इमेज-एम्बेड-कोड-जनरेटर', te: 'image-embed-code-generator-ని-తయారుచేయండి', 'zh-Hant': '圖片-embed-代碼-生成器' },
  'image-url-for-chatgpt': { en: 'image-url-for-chatgpt', hi: 'chatgpt-के-लिए-image-url-प्राप्त-करें', es: 'url-de-imagen-para-chatgpt', fr: 'url-image-pour-chatgpt', de: 'bild-url-fuer-chatgpt-erstellen', ja: 'chatgpt-画像url-変換', 'zh-Hans': 'chatgpt-tupian-lianjie', id: 'url-gambar-untuk-chatgpt', vi: 'tao-url-anh-cho-chatgpt', 'pt-BR': 'url-de-imagem-para-chatgpt', tr: 'chatgpt-icin-resim-url-olustur', tl: 'image-url-para-sa-chatgpt', pl: 'url-obrazu-dla-chatgpt', nl: 'afbeeldings-url-voor-chatgpt', it: 'url-immagini-per-chatgpt', ar: 'روابط-صور-لـ-chatgpt', bn: 'chatgpt-এর-জন্য-ইমেজ-url', fa: 'دریافت-لینک-تصویر-برای-chatgpt', ur: 'chatgpt-کے-لیے-تصویری-لنک', ru: 'ссылка-на-изображение-для-chatgpt', th: 'แปลง-รูปภาพ-เป็น-url-สำหรับ-chatgpt', ko: 'chatgpt-이미지-url-변환', sw: 'pata-url-za-picha-kwa-chatgpt', ms: 'dapatkan-url-imej-chatgpt', ta: 'chatgpt-க்கு-பட-url-களைப்-பெறுக', mr: 'chatgpt-साठी-इमेज-url-मिळवा', te: 'chatgpt-కోసం-చిత్రం-url', 'zh-Hant': 'chatgpt-圖片連結-產生器' },
  'image-to-url-for-whatsapp': { en: 'image-to-url-for-whatsapp', hi: 'whatsapp-पर-इमेज-लिंक-शेयर-करें', es: 'compartir-imagenes-whatsapp-url', fr: 'partager-images-whatsapp-url', de: 'bilder-auf-whatsapp-teilen', ja: 'whatsapp-gazo-kyoyu', 'zh-Hans': 'whatsapp-图片-链接-分享', id: 'bagikan-gambar-whatsapp-url', vi: 'chia-se-anh-qua-url-whatsapp', 'pt-BR': 'compartilhar-imagens-whatsapp-link', tr: 'whatsapp-icin-resim-linki-olustur', tl: 'magbahagi-ng-larawan-sa-whatsapp', nl: 'afbeeldingen-delen-whatsapp', it: 'condividi-immagini-whatsapp-url', ar: 'مشاركة-الصور-عبر-رابط-واتساب', bn: 'whatsapp-এ-ছবি-শেয়ার-করুন', fa: 'اشتراک-تصویر-در-واتس-اپ', ur: 'واٹس-ایپ-کے-لیے-تصویر-کا-لنک', ru: 'ssylki-na-izobrazheniya-dlya-whatsapp', th: 'แชร์-รูปภาพ-ผ่าน-ลิงก์-whatsapp', ko: 'whatsapp-이미지-링크-공유', sw: 'shiriki-picha-whatsapp', ms: 'kongsi-gambar-whatsapp-url', ta: 'வாட்ஸ்அப்பில்-படங்களை-பகிரவும்', mr: 'whatsapp-वर-इमेज-लिंक-शेअर-करा', te: 'వాట్సాప్-కోసం-ఇమేజ్-యుఆర్ఎల్', 'zh-Hant': 'whatsapp-圖片連結分享', pl: 'udostepnianie-zdjec-przez-link-whatsapp' },
  'image-to-url-for-html': { en: 'image-to-url-for-html', hi: 'html-के-लिए-image-to-url', es: 'imagen-a-url-html', fr: 'convertir-image-url-html', de: 'bild-zu-url-html', ja: '画像-を-url-に変換-html', 'zh-Hans': '图片-转-url-为-html', id: 'ubah-gambar-ke-url-html', vi: 'chuyen-anh-thanh-url-html', 'pt-BR': 'converter-imagem-para-url', tr: 'resimden-html-url-olustur', tl: 'larawan-papuntang-url-html', pl: 'obraz-na-url-dla-html', nl: 'afbeelding-naar-url-html', it: 'immagine-in-url-html', ar: 'تحويل-الصورة-إلى-url-لـ-html', bn: 'html-এর-জন্য-image-to-url', fa: 'تبدیل-تصویر-به-url-برای-html', ur: 'html-کے-لیے-image-to-url', ru: 'izobrazhenie-v-url-dlya-html', th: 'แปลง-image-เป็น-url-สำหรับ-html', ko: '이미지를-html-url로-변환', sw: 'picha-kuwa-url-html', ms: 'tukar-imej-kepada-url', ta: 'html-க்கு-image-to-url', mr: 'html-साठी-image-to-url', te: 'html-కోసం-image-to-url', 'zh-Hant': '圖片-轉-url-for-html' },
  'image-to-url-vercel': { en: 'image-to-url-vercel', hi: 'vercel-के-लिए-image-to-url', es: 'imagen-a-url-vercel', fr: 'image-vers-url-vercel', de: 'bild-zu-url-vercel', ja: '画像-url-変換-vercel', 'zh-Hans': '图片-转-url-vercel', id: 'ubah-gambar-ke-url-vercel', vi: 'chuyen-anh-thanh-url-vercel', 'pt-BR': 'imagem-para-url-vercel', tr: 'resimden-url-vercel', tl: 'image-to-url-para-sa-vercel', pl: 'obraz-na-url-vercel', nl: 'afbeelding-naar-url-vercel', it: 'immagine-in-url-vercel', ar: 'تحويل-الصورة-إلى-url-لـ-vercel', bn: 'image-to-url-vercel-এ-ব্যবহার', fa: 'تبدیل-تصویر-به-url-برای-vercel', ur: 'image-to-url-کو-vercel-کے-لیے-استعمال-کریں', ru: 'izobrazhenie-v-url-dlya-vercel', th: 'แปลง-รูปภาพ-เป็น-url-สำหรับ-vercel', ko: '이미지-url-변환-vercel', sw: 'picha-kwa-url-vercel', ms: 'imej-kepada-url-vercel', ta: 'image-to-url-vercel-க்கு', mr: 'image-to-url-vercel-साठी', te: 'vercel-కోసం-image-to-url', 'zh-Hant': '圖片-轉-url-vercel' },
  'image-hosting-for-wordpress': { en: 'image-hosting-for-wordpress', hi: 'वर्डप्रेस-के-लिए-इमेज-होस्टिंग', es: 'alojamiento-imagenes-wordpress', fr: 'hebergement-images-wordpress', de: 'bildhosting-fuer-wordpress', ja: 'wordpress-画像ホスティング-高速化', 'zh-Hans': 'wordpress-图片托管-加速', id: 'hosting-gambar-wordpress', vi: 'luu-tru-anh-wordpress', tr: 'wordpress-icin-gorsel-barindirma', tl: 'image-hosting-para-sa-wordpress', pl: 'hosting-obrazow-dla-wordpress', nl: 'afbeelding-hosting-voor-wordpress', it: 'hosting-immagini-wordpress', bn: 'ওয়ার্ডপ্রেস-ইমেজ-হোস্টিং', ur: 'ورڈپریس-کے-لیے-امیج-ہوسٹنگ', ru: 'хостинг-изображений-wordpress', th: 'โฮสต์รูปภาพ-wordpress-เพิ่มความเร็ว', ko: 'wordpress-이미지-호스팅-속도-향상', sw: 'uhifadhi-picha-kwa-wordpress', ms: 'hos-imej-wordpress-percuma', ta: 'wordpress-பட-ஹோஸ்டிங்', mr: 'wordpress-साठी-इमेज-होस्टिंग', te: 'వర్డ్-ప్రెస్-కోసం-ఇమేజ్-హోస్టింగ్', 'zh-Hant': 'wordpress-圖片託管-加速', 'pt-BR': 'hospedagem-de-imagens-wordpress', ar: 'استضافة-صور-wordpress', fa: 'میزبانی-تصویر-وردپرس' },
  'image-hosting-for-discord': { en: 'image-hosting-for-discord', hi: 'discord-के-लिए-इमेज-होस्टिंग', es: 'alojamiento-imagenes-discord', fr: 'hebergement-image-discord', de: 'bild-hosting-fuer-discord', ja: 'discord-用-画像-ホスティング', 'zh-Hans': 'discord-专用-图片-托管', id: 'hosting-gambar-discord', vi: 'luu-tru-anh-discord', 'pt-BR': 'hospedagem-imagens-discord', tr: 'discord-icin-gorsel-barindirma', tl: 'image-hosting-para-sa-discord', pl: 'hosting-zdjec-dla-discord', nl: 'image-hosting-voor-discord', it: 'hosting-immagini-discord', ar: 'استضافة-صور-لـ-discord', bn: 'discord-এর-জন্য-ইমেজ-হোস্টিং', fa: 'میزبانی-تصویر-برای-discord', ur: 'discord-کے-لیے-امیج-ہوسٹنگ', ru: 'hosting-izobrazheniy-dlya-discord', th: 'โฮสต์รูปภาพ-สำหรับ-discord', ko: 'discord-이미지-호스팅', sw: 'hosting-ya-picha-kwa-discord', ms: 'hosting-imej-untuk-discord', ta: 'discord-க்கான-பட-ஹோஸ்டிங்', mr: 'discord-साठी-इमेज-होस्टिंग', te: 'discord-కోసం-image-hosting', 'zh-Hant': 'discord-圖片託管' },
  'image-hosting-for-ebay': { en: 'image-hosting-for-ebay', hi: 'ebay-के-लिए-इमेज-होस्टिंग', es: 'alojamiento-imagenes-ebay', fr: 'hebergement-images-ebay', de: 'bildhosting-fuer-ebay', ja: 'ebay-出品用-画像ホスティング', 'zh-Hans': 'ebay-商品-图片-托管', id: 'hosting-gambar-ebay', vi: 'luu-tru-anh-ebay', 'pt-BR': 'hospedagem-imagens-ebay', tr: 'ebay-icin-gorsel-yukleme', tl: 'libreng-image-hosting-ebay', pl: 'darmowy-hosting-zdjec-ebay', nl: 'gratis-image-hosting-ebay', it: 'hosting-immagini-ebay', ar: 'استضافة-صور-لـ-ebay', bn: 'ebay-এর-জন্য-ইমেজ-হোস্টিং', fa: 'میزبانی-تصویر-برای-ebay', ur: 'ebay-کے-لیے-image-hosting', ru: 'hosting-izobrazheniy-dlya-ebay', th: 'โฮสต์รูปภาพ-ebay', ko: 'ebay-이미지-호스팅', sw: 'hosting-ya-picha-ebay', ms: 'hos-imej-ebay', ta: 'ebay-பட்டியல்களுக்கு-பட-ஹோஸ்டிங்', mr: 'ebay-साठी-इमेज-होस्टिंग', te: 'ebay-లిస్టింగ్స్-కోసం-image-హోస్టింగ్', 'zh-Hant': 'ebay-圖片託管' },
  'image-hosting-for-email-signatures': { en: 'image-hosting-for-email-signatures', hi: 'ईमेल-हस्ताक्षर-के-लिए-इमेज-होस्टिंग', es: 'alojamiento-imagenes-firmas-email', fr: 'hebergement-images-signature-email', de: 'bildhosting-fuer-e-mail-signaturen', ja: 'メール署名-画像ホスティング', 'zh-Hans': '电子邮件签名-图片托管', id: 'hosting-gambar-tanda-tangan-email', vi: 'luu-tru-anh-chu-ky-email', 'pt-BR': 'hospedagem-imagens-assinatura-email', tr: 'e-posta-imzasi-icin-gorsel-barindirma', tl: 'image-hosting-para-sa-email-signature', pl: 'hosting-obrazow-do-podpisow-email', nl: 'afbeelding-hosting-e-mailhandtekening', it: 'hosting-immagini-firme-email', ar: 'استضافة-صور-توقيع-البريد-الإلكتروني', bn: 'ইমেইল-সিগনেচার-ইমেজ-হোস্টিং', fa: 'میزبانی-تصویر-امضای-ایمیل', ur: 'ایمیل-دستخط-کے-لیے-تصویر-کی-میزبانی', ru: 'хостинг-изображений-для-подписей', th: 'โฮสต์รูปภาพ-ลายเซ็นอีเมล', ko: '이메일-서명-이미지-호스팅', sw: 'hosting-ya-picha-za-saini-za-barua-pepe', ms: 'hos-imej-tandatangan-emel', ta: 'மின்னஞ்சல்-கையொப்பம்-பட-இணைப்பு', mr: 'ईमेल-स्वाक्षरी-प्रतिमा-होस्टिंग', te: 'ఈమెయిల్-సిగ్నేచర్-ఇమేజ్-హోస్టింగ్', 'zh-Hant': '電子郵件簽名-圖片託管' },
  'image-hosting-for-forums': { en: 'image-hosting-for-forums', hi: 'फोरम-के-लिए-इमेज-होस्टिंग', es: 'alojamiento-imagenes-foros', fr: 'hebergement-images-forums', de: 'bildhosting-fuer-foren', ja: '掲示板用-画像-hosting', 'zh-Hans': '论坛-图片-托管', id: 'hosting-gambar-forum', vi: 'luu-tru-anh-dien-dan', 'pt-BR': 'hospedagem-imagens-foruns', tr: 'forumlar-icin-gorsel-yukleme', tl: 'libreng-image-hosting-forum', pl: 'darmowy-hosting-zdjec-na-fora', nl: 'gratis-afbeelding-hosting-forum', it: 'hosting-immagini-per-forum', ar: 'استضافة-صور-لـ-المنتديات', bn: 'ফোরামের-জন্য-ইমেজ-হোস্টিং', fa: 'میزبانی-تصویر-برای-انجمن', ur: 'فورم-کے-لیے-image-hosting', ru: 'besplatnyy-hosting-izobrazheniy-dlya-forumov', th: 'ฝากรูป-สำหรับ-ฟอรัม', ko: '포럼용-무료-이미지-호스팅', sw: 'hosting-ya-picha-kwa-forum', ms: 'hosting-gambar-forum', ta: 'மன்றங்களுக்கு-இலவச-image-hosting', mr: 'फोरमसाठी-मोफत-image-hosting', te: 'ఫోరమ్-పోస్ట్-ల-కోసం-image-hosting', 'zh-Hant': '論壇-圖片-託管' },
  'image-hosting-for-github-readme': { en: 'image-hosting-for-github-readme', hi: 'github-readme-के-लिए-इमेज-होस्टिंग', es: 'alojamiento-imagenes-github-readme', de: 'bildhosting-fuer-github-readme', ja: 'github-readme-gazou-hozon', 'zh-Hans': 'github-readme-tupian-tuoguan', id: 'hosting-gambar-github-readme', 'pt-BR': 'hospedagem-de-imagens-github', tr: 'github-readme-icin-gorsel-barindirma', tl: 'image-hosting-para-sa-github-readme', pl: 'hosting-obrazow-github-readme', nl: 'afbeeldingen-hosten-github-readme', it: 'hosting-immagini-github-readme', ar: 'استضافة-صور-github-readme', fa: 'میزبانی-تصویر-برای-گیت-هاب', ur: 'github-readme-کے-لیے-تصویر-کی-میزبانی', ru: 'khosting-izobrazheniy-dlya-github-readme', th: 'โฮสต์-รูปภาพ-github-readme', ko: 'github-readme-이미지-호스팅', sw: 'uhifadhi-picha-kwa-github-readme', ms: 'hos-imej-github-readme', ta: 'github-readme-படங்களை-பதிவேற்றவும்', 'zh-Hant': 'github-readme-圖片託管', fr: 'hebergement-images-github-readme', vi: 'luu-tru-anh-github-readme', mr: 'github-readme-साठी-इमेज-होस्टिंग', te: 'github-readme-కోసం-image-hosting' },
  'image-hosting-for-google-forms': { en: 'image-hosting-for-google-forms', hi: 'google-forms-के-लिए-image-url', es: 'urls-imagenes-google-forms', fr: 'url-images-google-forms', de: 'bild-urls-fuer-google-forms', ja: 'google-forms-gazou-url', 'zh-Hans': 'google-forms-tupian-lianjie', id: 'url-gambar-google-forms', vi: 'url-anh-cho-google-forms', 'pt-BR': 'urls-de-imagem-para-google-forms', tr: 'google-forms-icin-gorsel-url', tl: 'mga-url-ng-larawan-para-sa-google-forms', pl: 'adresy-url-obrazow-google-forms', nl: 'afbeelding-urls-google-forms', it: 'url-immagini-google-forms', ar: 'روابط-صور-لنماذج-جوجل', bn: 'google-forms-এ-ছবি-যোগ-করুন', fa: 'افزودن-تصویر-به-google-forms', ur: 'google-forms-ke-liye-tasweer-ke-url', ru: 'url-izobrazheniy-dlya-google-forms', th: 'ลิงก์รูปภาพสำหรับ-google-forms', ko: 'google-forms-이미지-url-추가', sw: 'url-za-picha-kwa-google-forms', ms: 'url-gambar-untuk-google-forms', ta: 'google-forms-ku-image-url-gal', 'zh-Hant': 'google-forms-圖片連結', mr: 'google-forms-साठी-इमेज-url', te: 'google-forms-ki-image-urls' },
  'image-hosting-for-google-sheets': { en: 'image-hosting-for-google-sheets', hi: 'google-sheets-के-लिए-image-url', es: 'urls-imagenes-google-sheets', fr: 'urls-images-google-sheets', de: 'bild-urls-fuer-google-sheets', ja: 'google-sheets-image-url-sakusei', 'zh-Hans': 'google-sheets-图片链接', id: 'url-gambar-google-sheets', vi: 'url-anh-cho-google-sheets', 'pt-BR': 'urls-de-imagem-google-sheets', tr: 'google-sheets-icin-resim-url', tl: 'mga-image-url-para-sa-google-sheets', pl: 'url-obrazow-dla-google-sheets', nl: 'afbeeldings-url-google-sheets', it: 'url-immagini-google-sheets', ar: 'روابط-صور-لجداول-بيانات-google', bn: 'google-sheets-এর-জন্য-ইমেজ-url', fa: 'لینک-تصویر-برای-google-sheets', ur: 'google-sheets-ke-liye-image-url', ru: 'url-izobrazheniy-dlya-google-sheets', th: 'ลิงก์รูปภาพสำหรับ-google-sheets', ko: '구글-스프레드시트-이미지-url', sw: 'url-za-picha-kwa-google-sheets', ms: 'url-gambar-google-sheets', ta: 'google-sheets-பயன்பாட்டிற்கான-பட-url', mr: 'google-sheets-साठी-इमेज-url', te: 'google-sheets-image-url-gen', 'zh-Hant': 'google-sheets-圖片連結' },
  'image-hosting-for-newsletters': { en: 'image-hosting-for-newsletters', hi: 'ईमेल-न्यूज़लेटर-के-लिए-इमेज-होस्टिंग', es: 'alojamiento-imagenes-boletines', fr: 'hebergement-images-newsletter', de: 'bildhosting-fuer-newsletter', ja: 'メールマガジン用画像ホスティング', 'zh-Hans': '邮件通讯-图片托管', id: 'hosting-gambar-newsletter-email', vi: 'luu-tru-anh-ban-tin', 'pt-BR': 'hospedagem-de-imagens-para-newsletters', tr: 'e-bulten-icin-gorsel-barindirma', tl: 'image-hosting-para-sa-newsletter', pl: 'hosting-obrazow-do-newsletterow', nl: 'afbeelding-hosting-nieuwsbrieven', it: 'hosting-immagini-newsletter', ar: 'استضافة-صور-النشرات-البريدية', bn: 'ইমেইল-নিউজলেটার-ইমেজ-হোস্টিং', fa: 'میزبانی-تصویر-خبرنامه', ur: 'ایمیل-نیوزلیٹر-کے-لیے-تصویر-کی-میزبانی', ru: 'khosting-izobrazheniy-dlya-rassylok', th: 'โฮสต์-รูปภาพ-จดหมายข่าว', ko: '뉴스레터-이미지-호스팅', sw: 'uhifadhi-picha-za-jarida', ms: 'hos-imej-untuk-buletin-emel', ta: 'மின்னஞ்சல்-செய்திமடல்-படங்கள்', mr: 'ईमेल-न्यूजलेटर-इमेज-होस्टिंग', te: 'ఈమెయిల్-న్యూస్-లెటర్-ఇమేజ్-హోస్టింగ్', 'zh-Hant': '電子報-圖片託管' },
  'image-hosting-for-notion': { en: 'image-hosting-for-notion', hi: 'notion-के-लिए-स्थायी-इमेज-लिंक', es: 'alojamiento-imagenes-notion', fr: 'hebergement-images-notion', de: 'dauerhafte-bild-urls-fuer-notion', ja: 'notion-画像-永続化', 'zh-Hans': 'notion-tupian-wai-lian', id: 'hosting-gambar-notion-permanen', vi: 'luu-tru-anh-notion', 'pt-BR': 'hospedagem-imagens-notion', tr: 'notion-icin-kalici-gorsel-barindirma', tl: 'permanenteng-url-ng-larawan-sa-notion', pl: 'hosting-obrazow-dla-notion', nl: 'permanente-afbeeldingslinks-voor-notion', it: 'hosting-immagini-per-notion', ar: 'استضافة-صور-notion', fa: 'میزبانی-تصویر-برای-نوشن', ru: 'хостинг-изображений-для-notion', th: 'โฮสต์รูปภาพ-notion-ถาวร', ko: 'notion-이미지-호스팅-영구-링크', sw: 'picha-za-kudumu-kwa-notion', ms: 'hos-imej-untuk-notion', ta: 'notion-பக்கங்களுக்கு-நிரந்தர-பட-இணைப்புகள்', mr: 'notion-साठी-इमेज-होस्टिंग', te: 'notion-చిత్రాలకు-శాశ్వత-url', 'zh-Hant': 'notion-圖片-永久連結', bn: 'notion-এর-জন্য-স্থায়ী-ইমেজ-লিঙ্ক', ur: 'notion-تصاویر-کے-لیے-مستقل-لنکس' },
  'image-hosting-for-shopify': { en: 'image-hosting-for-shopify', hi: 'shopify-के-लिए-फ्री-इमेज-होस्टिंग', es: 'alojamiento-imagenes-shopify', fr: 'hebergement-images-shopify', de: 'kostenloses-bild-hosting-shopify', ja: 'shopify-画像ホスティング', 'zh-Hans': 'shopify-图片托管', id: 'hosting-gambar-gratis-shopify', vi: 'luu-tru-anh-shopify', 'pt-BR': 'hospedagem-de-imagens-shopify', tl: 'libreng-image-hosting-para-sa-shopify', nl: 'gratis-image-hosting-voor-shopify', it: 'hosting-immagini-gratuito-shopify', ar: 'استضافة-صور-متاجر-shopify', bn: 'shopify-এর-জন্য-ফ্রি-ইমেজ-হোস্টিং', fa: 'میزبانی-تصویر-برای-shopify', ur: 'shopify-کے-لیے-مفت-امیج-ہوسٹنگ', ru: 'besplatnyy-khosting-izobrazheniy-shopify', ko: 'shopify-이미지-호스팅-무료', sw: 'hosting-ya-picha-kwa-shopify', ms: 'hos-imej-percuma-shopify', ta: 'shopify-கடைக்கான-இலவச-பட-ஹோஸ்டிங்', mr: 'shopify-साठी-मोफत-इमेज-होस्टिंग', te: 'shopify-స్టోర్-కోసం-ఉచిత-ఇమేజ్-హోస్టింగ్', 'zh-Hant': 'shopify-商店-免費圖片託管', tr: 'shopify-icin-ucretsiz-gorsel-barindirma', pl: 'darmowy-hosting-zdjec-shopify', th: 'โฮสต์-รูปภาพ-shopify-ฟรี' },
  'free-image-hosting': { en: 'free-image-hosting', hi: 'मुफ्त-image-होस्टिंग', es: 'alojamiento-imagenes-gratis', fr: 'hebergement-images-gratuit', de: 'kostenloses-image-hosting', ja: '無料-画像-ホスティング', 'zh-Hans': '免费-图片-托管', id: 'hosting-gambar-gratis', vi: 'luu-tru-anh-mien-phi', 'pt-BR': 'hospedagem-de-imagens-gratuita', tr: 'ucretsiz-resim-yukleme', tl: 'libreng-image-hosting', pl: 'darmowy-hosting-zdjec', nl: 'gratis-afbeeldingen-hosten', it: 'hosting-immagini-gratuito', ar: 'استضافة-صور-مجانية', bn: 'ফ্রি-image-হোস্টিং', fa: 'میزبانی-رایگان-تصویر', ur: 'مفت-image-hosting', ru: 'besplatnyy-hosting-izobrazheniy-imagetourl', th: 'บริการ-ฝากรูป-ฟรี', ko: '무료-이미지-호스팅', sw: 'hosting-ya-picha-bila-malipo', ms: 'hos-imej-percuma', ta: 'இலவச-image-hosting', mr: 'मोफत-image-होस्टिंग', te: 'ఉచిత-image-హోస్టింగ్', 'zh-Hant': '免費-圖片-託管' },
  'free-image-cdn': { en: 'free-image-cdn', hi: 'मुफ़्त-image-cdn', es: 'cdn-imagenes-gratis', fr: 'cdn-images-gratuit', de: 'kostenloses-image-cdn', ja: '無料-画像-cdn', 'zh-Hans': '免费-图片-cdn', id: 'cdn-gambar-gratis', vi: 'cdn-hinh-anh-mien-phi', 'pt-BR': 'cdn-de-imagens-gratuito', tr: 'ucretsiz-gorsel-cdn', tl: 'libreng-image-cdn', pl: 'darmowy-cdn-obrazow', nl: 'gratis-image-cdn', it: 'cdn-immagini-gratuito', ar: 'شبكة-cdn-صور-مجانية', bn: 'ফ্রি-ইমেজ-cdn', fa: 'cdn-رایگان-تصاویر', ur: 'مفت-image-cdn', ru: 'besplatnyy-cdn-dlya-izobrazheniy', th: 'cdn-รูปภาพ-ฟรี', ko: '무료-이미지-cdn', sw: 'cdn-ya-picha-bure', ms: 'cdn-imej-percuma', ta: 'இலவச-image-cdn', mr: 'मोफत-इमेज-cdn', te: 'ఉచిత-image-cdn', 'zh-Hant': '免費-圖片-cdn' },
  'ai-image-hosting': { en: 'ai-image-hosting', hi: 'ai-इमेज-होस्टिंग', es: 'alojamiento-imagenes-ia', fr: 'hebergement-images-ia', de: 'ki-bilder-hosten', ja: 'ai-画像-ホスティング', 'zh-Hans': 'ai-图像-托管', id: 'hosting-gambar-ai', vi: 'luu-tru-anh-ai', 'pt-BR': 'hospedagem-imagens-ia', tr: 'yapay-zeka-gorsel-barindirma', tl: 'libreng-ai-image-hosting', pl: 'hosting-grafik-ai', nl: 'ai-afbeeldingen-hosten', it: 'hosting-immagini-ai', ar: 'استضافة-صور-ai', bn: 'ai-ইমেজ-হোস্টিং', fa: 'میزبانی-تصاویر-ai', ur: 'ai-تصویر-کی-ہوسٹنگ', ru: 'hosting-ai-izobrazheniy', th: 'โฮสต์-รูปภาพ-ai', ko: 'ai-이미지-호스팅', sw: 'hosting-ya-picha-za-ai', ms: 'hos-imej-ai-percuma', ta: 'ai-பட-ஹோஸ்டிங்', mr: 'ai-इमेज-होस्टिंग', te: 'ai-image-హోస్టింగ్-ఉచితం', 'zh-Hant': 'ai-圖片託管' },
  'anonymous-image-upload': { en: 'anonymous-image-upload', hi: 'अनाम-image-अपलोड', es: 'subir-imagenes-anonimo', fr: 'hebergement-image-anonyme', de: 'anonymer-bild-upload', ja: '匿名-画像-アップロード', 'zh-Hans': '匿名-image-上传', id: 'unggah-gambar-anonim', vi: 'tai-anh-an-danh', 'pt-BR': 'upload-imagem-anonimo', tr: 'anonim-resim-yukle', tl: 'upload-ng-larawan-nang-anonymous', pl: 'anonimowe-przesylanie-zdjec', nl: 'anoniem-afbeeldingen-uploaden', it: 'upload-immagini-anonimo', ar: 'رفع-صور-مجهول-إلى-url', bn: 'বেনামী-image-আপলোড', fa: 'آپلود-ناشناس-تصویر', ur: 'گمنام-image-اپ-لوڈ', ru: 'anonimnaya-zagruzka-izobrazheniy', th: 'อัปโหลด-รูปภาพ-แบบ-ไม่ระบุตัวตน', ko: '익명-이미지-업로드', sw: 'pakia-picha-bila-jina', ms: 'muat-naik-imej-tanpa-nama', ta: 'அநாமதேய-image-பதிவேற்றம்', mr: 'अनामित-image-अपलोड', te: 'అజ్ఞాత-image-అప్-లోడ్', 'zh-Hant': '匿名-圖片-上傳' },
  'bulk-image-upload': { en: 'bulk-image-upload', hi: 'बल्क-इमेज-अपलोड', es: 'carga-masiva-imagenes', fr: 'telechargement-images-masse', de: 'bilder-massen-upload', ja: '画像-一括-アップロード', 'zh-Hans': '批量-图片-上传', id: 'unggah-gambar-massal', vi: 'tai-anh-hang-loat', 'pt-BR': 'upload-imagens-lote', tr: 'toplu-resim-yukleme', tl: 'upload-maramihang-larawan', pl: 'masowe-przesylanie-zdjec', nl: 'bulk-afbeeldingen-uploaden', it: 'caricamento-immagini-multiplo', ar: 'رفع-الصور-بالجملة', bn: 'বাল্ক-image-আপলোড', fa: 'آپلود-گروهی-تصاویر', ur: 'بلک-image-اپ-لوڈ', ru: 'massovaya-zagruzka-izobrazheniy', th: 'อัปโหลด-รูปภาพ-จำนวนมาก', ko: '대량-이미지-업로드', sw: 'pakia-picha-kwa-wingi', ms: 'muat-naik-imej-pukal', ta: 'மொத்தமாக-படங்களை-பதிவேற்றவும்', mr: 'बल्क-इमेज-अपलोड', te: 'బల్క్-image-అప్-లోడ్', 'zh-Hant': '大量-圖片-上傳' },
  'direct-image-link': { en: 'direct-image-link', hi: 'डायरेक्ट-इमेज-लिंक-होस्टिंग', es: 'enlaces-directos-imagenes', fr: 'hebergement-image-lien-direct', de: 'direkte-bild-links', ja: '画像-direct-link-作成', 'zh-Hans': '直接-image-链接', id: 'link-gambar-langsung', vi: 'hosting-anh-truc-tiep', 'pt-BR': 'link-direto-imagem', tr: 'dogrudan-resim-linki', tl: 'direktang-link-ng-larawan', pl: 'bezposrednie-linki-do-zdjec', nl: 'directe-afbeeldingslink-hosting', it: 'link-diretti-immagini', ar: 'روابط-صور-مباشرة', bn: 'ডাইরেক্ট-ইমেজ-লিঙ্ক', fa: 'لینک-مستقیم-تصویر', ur: 'براہ-راست-image-لنک', ru: 'pryamye-ssylki-na-izobrazheniya', th: 'ลิงก์-รูปภาพ-โดยตรง', ko: '다이렉트-이미지-link', sw: 'viungo-vya-picha-moja-kwa-moja', ms: 'pautan-imej-terus', ta: 'நேரடி-பட-இணைப்பு-url', mr: 'थेट-image-लिंक', te: 'డైరెక్ట్-image-లింక్', 'zh-Hant': '直接-image-連結' },
  'permanent-image-hosting': { en: 'permanent-image-hosting', hi: 'स्थायी-इमेज-टू-यूआरएल', fr: 'image-vers-url-permanent', de: 'bild-zu-url-dauerhaft', ja: '画像-url-永続化', 'zh-Hans': '永久图片链接托管', id: 'ubah-gambar-ke-url-permanen', vi: 'chuyen-anh-thanh-url-vinh-vien', 'pt-BR': 'imagem-para-url-permanente', tr: 'kalici-gorsel-url-donusturucu', tl: 'larawan-sa-url-na-permanente', pl: 'obraz-na-url-na-zawsze', nl: 'afbeelding-naar-url-permanent', it: 'immagine-a-url-permanente', ar: 'تحويل-الصورة-إلى-رابط-دائم', bn: 'স্থায়ী-ইমেজ-টু-ইউআরএল', fa: 'تبدیل-تصویر-به-لینک-دائمی', ur: 'تصویر-کو-مستقل-url-میں-بدلیں', ru: 'vechnaya-ssylka-na-izobrazhenie', th: 'แปลง-รูปภาพ-เป็น-ลิงก์-ถาวร', sw: 'picha-kuwa-url-ya-kudumu', ta: 'படத்தை-url-ஆக-மாற்றுதல்', mr: 'कायमस्वरूपी-इमेज-टू-यूआरएल', te: 'చిత్రం-నుండి-url-శాశ్వతం', 'zh-Hant': '永久圖片轉網址', es: 'imagen-a-url-permanente', ko: '영구-이미지-url-생성', ms: 'tukar-gambar-kepada-url-kekal' },
  'imgbb-alternative': { en: 'imgbb-alternative', hi: 'imgbb-का-बेहतर-विकल्प', es: 'alternativa-a-imgbb', fr: 'alternative-imgbb-gratuite', de: 'imgbb-alternative-kostenlos', ja: 'imgbb-no-daitai-service', 'zh-Hans': 'imgbb-zui-jia-ti-dai-pin', id: 'alternatif-imgbb-terbaik', vi: 'thay-the-imgbb', 'pt-BR': 'alternativa-ao-imgbb', tr: 'imgbb-alternatifi', tl: 'alternatibong-imgbb-mas-mabilis', pl: 'alternatywa-dla-imgbb', nl: 'imgbb-alternatief-gratis', it: 'alternativa-a-imgbb', ar: 'بديل-imgbb-سريع', bn: 'imgbb-এর-সেরা-বিকল্প', fa: 'جایگزین-imgbb', ur: 'imgbb-کا-بہترین-متبادل', ru: 'alternativa-imgbb-besplatno', th: 'ทางเลือก-imgbb-ที่ดีกว่า', ko: 'imgbb-대체-서비스', sw: 'mbadala-wa-imgbb-bila-matangazo', ms: 'alternatif-imgbb-terbaik', ta: 'imgbb-மாற்று-இலவச-பட-பதிவேற்றம்', mr: 'imgbb-चा-उत्तम-पर्याय', te: 'imgbb-కు-ఉత్తమ-ప్రత్యామ్నాయం', 'zh-Hant': 'imgbb-最佳替代方案' },
  'imgur-alternative': { en: 'imgur-alternative', hi: 'सर्वश्रेष्ठ-imgur-विकल्प', fr: 'meilleure-alternative-imgur', de: 'beste-imgur-alternative', ja: 'imgur-no-daitai-service', 'zh-Hans': '最佳-imgur-替代品', id: 'alternatif-imgur-terbaik', vi: 'thay-the-imgur-tot-nhat', 'pt-BR': 'melhor-alternativa-ao-imgur', tr: 'en-iyi-imgur-alternatifi', tl: 'pinakamahusay-na-alternatibo-sa-imgur', pl: 'najlepsza-alternatywa-dla-imgur', nl: 'beste-imgur-alternatief', it: 'migliore-alternativa-imgur', ar: 'افضل-بديل-لـ-imgur', bn: 'সেরা-imgur-বিকল্প', fa: 'بهترین-جایگزین-imgur', ur: 'بہترین-imgur-متبادل', ru: 'luchshaya-alternativa-imgur', th: 'ทางเลือก-imgur-ที่ดีที่สุด', ko: '최고의-imgur-대안', sw: 'mbadala-bora-wa-imgur', ms: 'alternatif-imgur-terbaik', ta: 'சிறந்த-imgur-மாற்று', mr: 'सर्वोत्तम-imgur-पर्याय', te: 'ఉత్తమ-imgur-ప్రత్యామ్నాయం', 'zh-Hant': 'imgur-最佳替代方案', es: 'mejor-alternativa-a-imgur' },
  'cloudinary-alternative': { en: 'cloudinary-alternative', hi: 'cloudinary-का-विकल्प', es: 'alternativa-a-cloudinary', fr: 'alternative-cloudinary', de: 'cloudinary-alternative', ja: 'cloudinary-の-代替', 'zh-Hans':'cloudinary-替代品', id: 'alternatif-cloudinary', vi: 'thay-the-cloudinary', 'pt-BR': 'alternativa-ao-cloudinary', tr: 'cloudinary-alternatifi', tl: 'alternatibo-sa-cloudinary', pl: 'alternatywa-dla-cloudinary', nl: 'cloudinary-alternatief', it: 'alternativa-a-cloudinary', ar: 'بديل-cloudinary', bn: 'cloudinary-এর-বিকল্প', fa: 'جایگزین-cloudinary', ur: 'cloudinary-کا-متبادل', ru: 'alternativa-cloudinary', th: 'ทางเลือก-cloudinary', ko: 'cloudinary-대체', sw: 'mbadala-wa-cloudinary', ms: 'alternatif-cloudinary', ta: 'cloudinary-மாற்று', mr: 'cloudinary-चा-पर्याय', te: 'cloudinary-ప్రత్యామ్నాయం', 'zh-Hant':'cloudinary-替代方案' },
  // Cluster A — format-pair converters
  'png-to-jpg': { en: 'png-to-jpg', hi: 'png-को-jpg-में-बदलें', es: 'convertir-png-a-jpg', fr: 'convertir-png-en-jpg', de: 'png-in-jpg-umwandeln', ja: 'png-を-jpg-に変換', 'zh-Hans': 'png-转-jpg', id: 'ubah-png-ke-jpg', vi: 'chuyen-png-sang-jpg', 'pt-BR': 'converter-png-para-jpg', tr: 'png-jpg-donusturucu', tl: 'i-convert-ang-png-sa-jpg', pl: 'konwertuj-png-na-jpg', nl: 'png-naar-jpg-converteren', it: 'converti-png-in-jpg', ar: 'تحويل-png-إلى-jpg', bn: 'png-থেকে-jpg-কনভার্টার', fa: 'تبدیل-png-به-jpg', ur: 'png-کو-jpg-میں-تبدیل', ru: 'konvertirovat-png-v-jpg', th: 'แปลง-png-เป็น-jpg', ko: 'png-jpg-변환', sw: 'badilisha-png-kuwa-jpg', ms: 'tukar-png-ke-jpg', ta: 'png-ஐ-jpg-ஆக-மாற்று', mr: 'png-ला-jpg-मध्ये-बदला', te: 'png-ని-jpg-గా-మార్చు', 'zh-Hant': 'png-轉-jpg' },
  'jpg-to-png': { en: 'jpg-to-png', hi: 'jpg-को-png-में-बदलें', es: 'convertir-jpg-a-png', fr: 'convertir-jpg-en-png', de: 'jpg-in-png-umwandeln', ja: 'jpg-を-png-に変換', 'zh-Hans': 'jpg-转-png', id: 'ubah-jpg-ke-png', vi: 'chuyen-jpg-sang-png', 'pt-BR': 'converter-jpg-para-png', tr: 'jpg-png-donusturucu', tl: 'i-convert-ang-jpg-sa-png', pl: 'konwertuj-jpg-na-png', nl: 'jpg-naar-png-converteren', it: 'converti-jpg-in-png', ar: 'تحويل-jpg-إلى-png', bn: 'jpg-থেকে-png-কনভার্টার', fa: 'تبدیل-jpg-به-png', ur: 'jpg-کو-png-میں-تبدیل', ru: 'konvertirovat-jpg-v-png', th: 'แปลง-jpg-เป็น-png', ko: 'jpg-png-변환', sw: 'badilisha-jpg-kuwa-png', ms: 'tukar-jpg-ke-png', ta: 'jpg-ஐ-png-ஆக-மாற்று', mr: 'jpg-ला-png-मध्ये-बदला', te: 'jpg-ని-png-గా-మార్చు', 'zh-Hant': 'jpg-轉-png' },
  'webp-to-jpg': { en: 'webp-to-jpg', hi: 'webp-को-jpg-में-बदलें', es: 'convertir-webp-a-jpg', fr: 'convertir-webp-en-jpg', de: 'webp-in-jpg-umwandeln', ja: 'webp-を-jpg-に変換', 'zh-Hans': 'webp-转-jpg', id: 'ubah-webp-ke-jpg', vi: 'chuyen-webp-sang-jpg', 'pt-BR': 'converter-webp-para-jpg', tr: 'webp-jpg-donusturucu', tl: 'i-convert-ang-webp-sa-jpg', pl: 'konwertuj-webp-na-jpg', nl: 'webp-naar-jpg-converteren', it: 'converti-webp-in-jpg', ar: 'تحويل-webp-إلى-jpg', bn: 'webp-থেকে-jpg-কনভার্টার', fa: 'تبدیل-webp-به-jpg', ur: 'webp-کو-jpg-میں-تبدیل', ru: 'konvertirovat-webp-v-jpg', th: 'แปลง-webp-เป็น-jpg', ko: 'webp-jpg-변환', sw: 'badilisha-webp-kuwa-jpg', ms: 'tukar-webp-ke-jpg', ta: 'webp-ஐ-jpg-ஆக-மாற்று', mr: 'webp-ला-jpg-मध्ये-बदला', te: 'webp-ని-jpg-గా-మార్చు', 'zh-Hant': 'webp-轉-jpg' },
  'webp-to-png': { en: 'webp-to-png', hi: 'webp-को-png-में-बदलें', es: 'convertir-webp-a-png', fr: 'convertir-webp-en-png', de: 'webp-in-png-umwandeln', ja: 'webp-を-png-に変換', 'zh-Hans': 'webp-转-png', id: 'ubah-webp-ke-png', vi: 'chuyen-webp-sang-png', 'pt-BR': 'converter-webp-para-png', tr: 'webp-png-donusturucu', tl: 'i-convert-ang-webp-sa-png', pl: 'konwertuj-webp-na-png', nl: 'webp-naar-png-converteren', it: 'converti-webp-in-png', ar: 'تحويل-webp-إلى-png', bn: 'webp-থেকে-png-কনভার্টার', fa: 'تبدیل-webp-به-png', ur: 'webp-کو-png-میں-تبدیل', ru: 'konvertirovat-webp-v-png', th: 'แปลง-webp-เป็น-png', ko: 'webp-png-변환', sw: 'badilisha-webp-kuwa-png', ms: 'tukar-webp-ke-png', ta: 'webp-ஐ-png-ஆக-மாற்று', mr: 'webp-ला-png-मध्ये-बदला', te: 'webp-ని-png-గా-మార్చు', 'zh-Hant': 'webp-轉-png' },
  'png-to-webp': { en: 'png-to-webp', hi: 'png-को-webp-में-बदलें', es: 'convertir-png-a-webp', fr: 'convertir-png-en-webp', de: 'png-in-webp-umwandeln', ja: 'png-を-webp-に変換', 'zh-Hans': 'png-转-webp', id: 'ubah-png-ke-webp', vi: 'chuyen-png-sang-webp', 'pt-BR': 'converter-png-para-webp', tr: 'png-webp-donusturucu', tl: 'i-convert-ang-png-sa-webp', pl: 'konwertuj-png-na-webp', nl: 'png-naar-webp-converteren', it: 'converti-png-in-webp', ar: 'تحويل-png-إلى-webp', bn: 'png-থেকে-webp-কনভার্টার', fa: 'تبدیل-png-به-webp', ur: 'png-کو-webp-میں-تبدیل', ru: 'konvertirovat-png-v-webp', th: 'แปลง-png-เป็น-webp', ko: 'png-webp-변환', sw: 'badilisha-png-kuwa-webp', ms: 'tukar-png-ke-webp', ta: 'png-ஐ-webp-ஆக-மாற்று', mr: 'png-ला-webp-मध्ये-बदला', te: 'png-ని-webp-గా-మార్చు', 'zh-Hant': 'png-轉-webp' },
  'jpg-to-webp': { en: 'jpg-to-webp', hi: 'jpg-को-webp-में-बदलें', es: 'convertir-jpg-a-webp', fr: 'convertir-jpg-en-webp', de: 'jpg-in-webp-umwandeln', ja: 'jpg-を-webp-に変換', 'zh-Hans': 'jpg-转-webp', id: 'ubah-jpg-ke-webp', vi: 'chuyen-jpg-sang-webp', 'pt-BR': 'converter-jpg-para-webp', tr: 'jpg-webp-donusturucu', tl: 'i-convert-ang-jpg-sa-webp', pl: 'konwertuj-jpg-na-webp', nl: 'jpg-naar-webp-converteren', it: 'converti-jpg-in-webp', ar: 'تحويل-jpg-إلى-webp', bn: 'jpg-থেকে-webp-কনভার্টার', fa: 'تبدیل-jpg-به-webp', ur: 'jpg-کو-webp-میں-تبدیل', ru: 'konvertirovat-jpg-v-webp', th: 'แปลง-jpg-เป็น-webp', ko: 'jpg-webp-변환', sw: 'badilisha-jpg-kuwa-webp', ms: 'tukar-jpg-ke-webp', ta: 'jpg-ஐ-webp-ஆக-மாற்று', mr: 'jpg-ला-webp-मध्ये-बदला', te: 'jpg-ని-webp-గా-మార్చు', 'zh-Hant': 'jpg-轉-webp' },
  'png-to-pdf': { en: 'png-to-pdf', hi: 'png-को-pdf-में-बदलें', es: 'convertir-png-a-pdf', fr: 'convertir-png-en-pdf', de: 'png-in-pdf-umwandeln', ja: 'png-を-pdf-に変換', 'zh-Hans': 'png-转-pdf', id: 'ubah-png-ke-pdf', vi: 'chuyen-png-sang-pdf', 'pt-BR': 'converter-png-para-pdf', tr: 'png-pdf-donusturucu', tl: 'i-convert-ang-png-sa-pdf', pl: 'konwertuj-png-na-pdf', nl: 'png-naar-pdf-converteren', it: 'converti-png-in-pdf', ar: 'تحويل-png-إلى-pdf', bn: 'png-থেকে-pdf-কনভার্টার', fa: 'تبدیل-png-به-pdf', ur: 'png-کو-pdf-میں-تبدیل', ru: 'konvertirovat-png-v-pdf', th: 'แปลง-png-เป็น-pdf', ko: 'png-pdf-변환', sw: 'badilisha-png-kuwa-pdf', ms: 'tukar-png-ke-pdf', ta: 'png-ஐ-pdf-ஆக-மாற்று', mr: 'png-ला-pdf-मध्ये-बदला', te: 'png-ని-pdf-గా-మార్చు', 'zh-Hant': 'png-轉-pdf' },
  'jpg-to-pdf': { en: 'jpg-to-pdf', hi: 'jpg-को-pdf-में-बदलें', es: 'convertir-jpg-a-pdf', fr: 'convertir-jpg-en-pdf', de: 'jpg-in-pdf-umwandeln', ja: 'jpg-を-pdf-に変換', 'zh-Hans': 'jpg-转-pdf', id: 'ubah-jpg-ke-pdf', vi: 'chuyen-jpg-sang-pdf', 'pt-BR': 'converter-jpg-para-pdf', tr: 'jpg-pdf-donusturucu', tl: 'i-convert-ang-jpg-sa-pdf', pl: 'konwertuj-jpg-na-pdf', nl: 'jpg-naar-pdf-converteren', it: 'converti-jpg-in-pdf', ar: 'تحويل-jpg-إلى-pdf', bn: 'jpg-থেকে-pdf-কনভার্টার', fa: 'تبدیل-jpg-به-pdf', ur: 'jpg-کو-pdf-میں-تبدیل', ru: 'konvertirovat-jpg-v-pdf', th: 'แปลง-jpg-เป็น-pdf', ko: 'jpg-pdf-변환', sw: 'badilisha-jpg-kuwa-pdf', ms: 'tukar-jpg-ke-pdf', ta: 'jpg-ஐ-pdf-ஆக-மாற்று', mr: 'jpg-ला-pdf-मध्ये-बदला', te: 'jpg-ని-pdf-గా-మార్చు', 'zh-Hant': 'jpg-轉-pdf' },
  'heic-to-png': { en: 'heic-to-png', hi: 'heic-को-png-में-बदलें', es: 'convertir-heic-a-png', fr: 'convertir-heic-en-png', de: 'heic-in-png-umwandeln', ja: 'heic-を-png-に変換', 'zh-Hans': 'heic-转-png', id: 'ubah-heic-ke-png', vi: 'chuyen-heic-sang-png', 'pt-BR': 'converter-heic-para-png', tr: 'heic-png-donusturucu', tl: 'i-convert-ang-heic-sa-png', pl: 'konwertuj-heic-na-png', nl: 'heic-naar-png-converteren', it: 'converti-heic-in-png', ar: 'تحويل-heic-إلى-png', bn: 'heic-থেকে-png-কনভার্টার', fa: 'تبدیل-heic-به-png', ur: 'heic-کو-png-میں-تبدیل', ru: 'konvertirovat-heic-v-png', th: 'แปลง-heic-เป็น-png', ko: 'heic-png-변환', sw: 'badilisha-heic-kuwa-png', ms: 'tukar-heic-ke-png', ta: 'heic-ஐ-png-ஆக-மாற்று', mr: 'heic-ला-png-मध्ये-बदला', te: 'heic-ని-png-గా-మార్చు', 'zh-Hant': 'heic-轉-png' },
  'heic-to-pdf': { en: 'heic-to-pdf', hi: 'heic-को-pdf-में-बदलें', es: 'convertir-heic-a-pdf', fr: 'convertir-heic-en-pdf', de: 'heic-in-pdf-umwandeln', ja: 'heic-を-pdf-に変換', 'zh-Hans': 'heic-转-pdf', id: 'ubah-heic-ke-pdf', vi: 'chuyen-heic-sang-pdf', 'pt-BR': 'converter-heic-para-pdf', tr: 'heic-pdf-donusturucu', tl: 'i-convert-ang-heic-sa-pdf', pl: 'konwertuj-heic-na-pdf', nl: 'heic-naar-pdf-converteren', it: 'converti-heic-in-pdf', ar: 'تحويل-heic-إلى-pdf', bn: 'heic-থেকে-pdf-কনভার্টার', fa: 'تبدیل-heic-به-pdf', ur: 'heic-کو-pdf-میں-تبدیل', ru: 'konvertirovat-heic-v-pdf', th: 'แปลง-heic-เป็น-pdf', ko: 'heic-pdf-변환', sw: 'badilisha-heic-kuwa-pdf', ms: 'tukar-heic-ke-pdf', ta: 'heic-ஐ-pdf-ஆக-மாற்று', mr: 'heic-ला-pdf-मध्ये-बदला', te: 'heic-ని-pdf-గా-మార్చు', 'zh-Hant': 'heic-轉-pdf' },
  // Cluster B — utilities
  'image-compressor': { en: 'image-compressor', hi: 'इमेज-कंप्रेसर', es: 'compresor-de-imagenes', fr: 'compresseur-d-images', de: 'bildkomprimierer', ja: '画像-圧縮-ツール', 'zh-Hans': '图片-压缩-工具', id: 'kompres-gambar', vi: 'nen-anh-online', 'pt-BR': 'compressor-de-imagens', tr: 'resim-sikistirici', tl: 'image-compressor-libre', pl: 'kompresor-obrazow', nl: 'afbeelding-comprimeren', it: 'compressore-immagini', ar: 'ضاغط-الصور', bn: 'ইমেজ-কম্প্রেসর', fa: 'فشرده-ساز-تصویر', ur: 'امیج-کمپریسر', ru: 'szhatie-izobrazheniy', th: 'บีบอัด-รูปภาพ', ko: '이미지-압축', sw: 'banisha-picha', ms: 'pemampat-imej', ta: 'படம்-சுருக்கி', mr: 'इमेज-कॉम्प्रेसर', te: 'చిత్రం-కుదింపు', 'zh-Hant': '圖片-壓縮-工具' },
  'image-resizer': { en: 'image-resizer', hi: 'इमेज-रीसाइज़र', es: 'redimensionar-imagen', fr: 'redimensionneur-d-images', de: 'bild-groesse-aendern', ja: '画像-サイズ-変更', 'zh-Hans': '图片-尺寸-调整', id: 'ubah-ukuran-gambar', vi: 'thay-doi-kich-thuoc-anh', 'pt-BR': 'redimensionar-imagens', tr: 'resim-boyutlandirma', tl: 'image-resizer-libre', pl: 'zmiana-rozmiaru-obrazu', nl: 'afbeelding-grootte-aanpassen', it: 'ridimensiona-immagini', ar: 'تغيير-حجم-الصورة', bn: 'ইমেজ-রিসাইজার', fa: 'تغییر-اندازه-تصویر', ur: 'امیج-ری-سائز-کرنا', ru: 'izmenenie-razmera-izobrazheniya', th: 'ปรับขนาด-รูปภาพ', ko: '이미지-크기-조정', sw: 'badilisha-ukubwa-wa-picha', ms: 'saiz-semula-imej', ta: 'பட-மறுஅளவு', mr: 'इमेज-रीसाइजर', te: 'చిత్రం-పరిమాణం-మార్చు', 'zh-Hant': '圖片-尺寸-調整' },
  'image-to-base64': { en: 'image-to-base64', hi: 'इमेज-को-base64-में-बदलें', es: 'imagen-a-base64', fr: 'image-vers-base64', de: 'bild-zu-base64', ja: '画像-を-base64-に変換', 'zh-Hans': '图片-转-base64', id: 'ubah-gambar-ke-base64', vi: 'chuyen-anh-thanh-base64', 'pt-BR': 'imagem-para-base64', tr: 'resim-base64-donustur', tl: 'image-sa-base64', pl: 'obraz-na-base64', nl: 'afbeelding-naar-base64', it: 'immagine-in-base64', ar: 'تحويل-الصورة-إلى-base64', bn: 'ইমেজ-থেকে-base64', fa: 'تبدیل-تصویر-به-base64', ur: 'امیج-کو-base64-میں-تبدیل', ru: 'izobrazhenie-v-base64', th: 'แปลง-รูปภาพ-เป็น-base64', ko: '이미지-base64-변환', sw: 'picha-kuwa-base64', ms: 'imej-kepada-base64', ta: 'படம்-base64-ஆக', mr: 'इमेज-ला-base64-मध्ये', te: 'చిత్రం-base64-గా', 'zh-Hant': '圖片-轉-base64' },
  'base64-to-image': { en: 'base64-to-image', hi: 'base64-को-इमेज-में-बदलें', es: 'base64-a-imagen', fr: 'base64-vers-image', de: 'base64-zu-bild', ja: 'base64-を-画像-に変換', 'zh-Hans': 'base64-转-图片', id: 'ubah-base64-ke-gambar', vi: 'chuyen-base64-thanh-anh', 'pt-BR': 'base64-para-imagem', tr: 'base64-resim-donustur', tl: 'base64-sa-image', pl: 'base64-na-obraz', nl: 'base64-naar-afbeelding', it: 'base64-in-immagine', ar: 'تحويل-base64-إلى-صورة', bn: 'base64-থেকে-ইমেজ', fa: 'تبدیل-base64-به-تصویر', ur: 'base64-کو-امیج-میں-تبدیل', ru: 'base64-v-izobrazhenie', th: 'แปลง-base64-เป็น-รูปภาพ', ko: 'base64-이미지-변환', sw: 'base64-kuwa-picha', ms: 'base64-kepada-imej', ta: 'base64-படம்-ஆக', mr: 'base64-ला-इमेज-मध्ये', te: 'base64-చిత్రం-గా', 'zh-Hant': 'base64-轉-圖片' },
  'favicon-generator': { en: 'favicon-generator', hi: 'फेविकॉन-जनरेटर', es: 'generador-de-favicon', fr: 'generateur-de-favicon', de: 'favicon-generator', ja: 'favicon-生成-ツール', 'zh-Hans': 'favicon-生成器', id: 'pembuat-favicon', vi: 'tao-favicon-online', 'pt-BR': 'gerador-de-favicon', tr: 'favicon-olusturucu', tl: 'favicon-generator-libre', pl: 'generator-favicon', nl: 'favicon-generator', it: 'generatore-favicon', ar: 'مولد-favicon', bn: 'ফেভিকন-জেনারেটর', fa: 'سازنده-favicon', ur: 'فیوی-کون-جنریٹر', ru: 'generator-favicon', th: 'สร้าง-favicon', ko: '파비콘-생성기', sw: 'kitengenezaji-favicon', ms: 'penjana-favicon', ta: 'ஃபேவிகான்-ஜெனரேட்டர்', mr: 'फेविकॉन-जनरेटर', te: 'ఫేవికాన్-జనరేటర్', 'zh-Hant': 'favicon-產生器' },
  'about': { en: 'about', hi: 'imagetourl-के-बारे-में', es: 'sobre-imagetourl', fr: 'a-propos-imagetourl', de: 'ueber-imagetourl', ja: 'imagetourl-について', 'zh-Hans': '关于-imagetourl', id: 'tentang-imagetourl', vi: 've-imagetourl', 'pt-BR': 'sobre-imagetourl', tr: 'imagetourl-hakkinda', tl: 'tungkol-sa-imagetourl', pl: 'o-imagetourl', nl: 'over-imagetourl', it: 'chi-siamo-imagetourl', ar: 'نبذة-عن-imagetourl', bn: 'imagetourl-সম্পর্কে', fa: 'درباره-imagetourl', ur: 'imagetourl-کے-بارے-میں', ru: 'o-servise-imagetourl', th: 'เกี่ยวกับ-imagetourl', ko: 'imagetourl-소개', sw: 'kuhusu-imagetourl', ms: 'tentang-imagetourl', ta: 'imagetourl-பற்றி', mr: 'imagetourl-बद्दल-माहिती', 'zh-Hant': '關於-imagetourl', te: 'imagetourl-గురించి' },
  'contact': { en: 'contact', hi: 'हमसे-संपर्क-करें', es: 'contacto-imagetourl', fr: 'contactez-imagetourl', de: 'kontakt-imagetourl', ja: 'お問い合わせ-imagetourl', 'zh-Hans': '联系-我们-支持', id: 'hubungi-imagetourl', vi: 'lien-he-imagetourl', 'pt-BR': 'fale-conosco', tr: 'imagetourl-iletisim', tl: 'makipag-ugnayan-sa-imagetourl', pl: 'kontakt-z-imagetourl', nl: 'contact-opnemen', it: 'contatta-imagetourl', ar: 'اتصل-بنا-imagetourl', bn: 'আমাদের-সাথে-যোগাযোগ', fa: 'تماس-با-ما', ur: 'ہم-سے-رابطہ-کریں', ru: 'svyazatsya-s-namy', th: 'ติดต่อ-เรา-imagetourl', ko: '문의하기-고객-지원', sw: 'wasiliana-nasi', ms: 'hubungi-kami', ta: 'எங்களைத்-தொடர்பு-கொள்ளுங்கள்', mr: 'आमच्याशी-संपर्क-साधा', te: 'మమ్మల్ని-సంప్రదించండి-imagetourl', 'zh-Hant': '聯絡-imagetourl-支援' },
  'content-guidelines': { en: 'content-guidelines', hi: 'कंटेंट-गाइडलाइन्स-और-नीति', es: 'directrices-de-contenido', fr: 'directives-de-contenu', de: 'inhaltsrichtlinien-und-nutzungsbedingungen', ja: 'コンテンツ-ガイドライン', 'zh-Hans': '内容-准则', id: 'panduan-konten-imagetourl', vi: 'huong-dan-noi-dung', 'pt-BR': 'diretrizes-de-conteudo', tr: 'icerik-kurallari-politikasi', tl: 'alituntunin-sa-nilalaman', pl: 'zasady-tresci-imagetourl', nl: 'inhoudsrichtlijnen-en-voorwaarden', it: 'linee-guida-contenuti', ar: 'إرشادات-المحتوى-imagetourl', bn: 'কন্টেন্ট-নির্দেশিকা-এবং-নীতি', fa: 'دستورالعمل-های-محتوا', ur: 'مواد-کے-رہنما-خطوط', ru: 'pravila-kontenta-imagetourl', th: 'แนวทาง-เนื้อหา-imagetourl', ko: '콘텐츠-가이드라인-정책', sw: 'mwongozo-wa-maudhui', ms: 'garis-panduan-kandungan', ta: 'உள்ளடக்க-வழிகாட்டுதல்கள்', mr: 'कंटेंट-मार्गदर्शक-तत्त्वे', te: 'కంటెంట్-మార్గదర్శకాలు', 'zh-Hant': '內容-規範-與-政策' },
};

export const PAGE_KEYS = Object.keys(SLUGS) as PageKey[];
